// apps/solid-trigger/src/App.tsx
import { toastManager } from "@org/toast-service";

export default function App() {
  return (
    <div
      style={
        {
          padding: "1rem",
          border: "2px solid #2c4f7c",
          height: "100%",
          "box-sizing": "border-box", // Solid prefers hyphenated attributes for styles inside objects or strings, or lowercase JS style object properties. Let's use standard literal string style or camelCase.
        } as any
      }
    >
      <h2 style={{ color: "#2c4f7c", "margin-top": 0 } as any}>SolidJS App</h2>
      <p>I am a SolidJS micro-frontend.</p>
      <button
        onClick={() => {
          toastManager.add({
            message: "Hello from the SolidJS App!",
            type: "info",
          });
        }}
        style={
          {
            padding: "10px 20px",
            background: "#2c4f7c",
            border: "none",
            "border-radius": "4px",
            cursor: "pointer",
            "font-weight": "bold",
            color: "white", // adding text color for better contrast
          } as any
        }
      >
        Fire Singleton Toast
      </button>
    </div>
  );
}

// apps/svelte-trigger/src/App.svelte
<script lang="ts">
  import { toastManager } from "@org/toast-service";

  function handleClick() {
    toastManager.add({
      message: "Hello from the Svelte App!",
      type: "info",
    });
  }
</script>

<div
  style="padding: 1rem; border: 2px solid #ff3e00; height: 100%; box-sizing: border-box;"
>
  <h2 style="color: #ff3e00; margin-top: 0;">Svelte App</h2>
  <p>I am a Svelte micro-frontend.</p>
  <button
    on:click={handleClick}
    style="padding: 10px 20px; background: #ff3e00; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; color: white;"
  >
    Fire Singleton Toast
  </button>
</div>
