// apps/preact-trigger/src/App.tsx
import { toastManager } from "@org/toast-service";

export default function App() {
  return (
    <div
      style={{
        padding: "1rem",
        border: "2px solid #8f61e1",
        height: "100%",
        boxSizing: "border-box",
      }}
    >
      <h2 style={{ color: "#8f61e1", marginTop: 0 }}>Preact App</h2>
      <p>I am a preact micro-frontend.</p>

      <button
        onClick={() =>
          toastManager.add({
            message: "Hello from the Preact App!",
            type: "error",
          })
        }
        style={{
          padding: "10px 20px",
          background: "#8f61e1",
          color: "#fff",
          border: "none",
          borderRadius: "4px",
          cursor: "pointer",
          fontWeight: "bold",
        }}
      >
        Fire Singleton Toast
      </button>
    </div>
  );
}

// apps/svelte-trigger/src/App.svelte
<script lang="ts">
  import { toastManager } from "@org/toast-service";

  function handleClick() {
    toastManager.add({
      message: "Hello from the Svelte App!",
      type: "info",
    });
  }
</script>

<div
  style="padding: 1rem; border: 2px solid #ff3e00; height: 100%; box-sizing: border-box;"
>
  <h2 style="color: #ff3e00; margin-top: 0;">Svelte App</h2>
  <p>I am a Svelte micro-frontend.</p>
  <button
    on:click={handleClick}
    style="padding: 10px 20px; background: #ff3e00; border: none; border-radius: 4px; cursor: pointer; font-weight: bold; color: white;"
  >
    Fire Singleton Toast
  </button>
</div>
